name: CI

on:
  push:
  pull_request:

jobs:
  build-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        compiler: [clang, gcc]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Install tools (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y clang gcc cppcheck clang-format valgrind
          sudo update-alternatives --set cc /usr/bin/${{ matrix.compiler }}

      - name: Install tools (macOS)
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install cppcheck clang-format
          if [[ "${{ matrix.compiler }}" != "clang" ]]; then
            echo "Skipping gcc on macOS (use clang)"; exit 0
          fi

      - name: Verify tools installation
        run: |
          echo "=== Проверка установленных инструментов ==="
          ${{ matrix.compiler }} --version
          cppcheck --version
          clang-format --version

      - name: Check clang-format
        run: scripts/check-format.sh

      - name: cppcheck
        run: scripts/check-cppcheck.sh

      - name: Build all
        run: make build

      - name: Test all (sanitizers)
        run: make test

      - name: Valgrind (Ubuntu only)
        if: runner.os == 'Linux'
        run: make valgrind
